/** EN-строки области «guest» (вход, восстановление, новый пароль, приглашение, главная, аккаунт, новая игра). Ключ — русская строка как в коде. Добавлять только сюда; legacy.ts не трогать. */
export const GUEST: Record<string, string> = {
  // Вход и регистрация
  "Вход или регистрация": "Sign in or sign up",
  "Почта": "Email",
  "Почта нужна, чтобы восстановить пароль и получать уведомления.": "Email is needed to recover your password and receive notifications.",
  "Создать аккаунт": "Create account",
  "На почту придёт письмо со ссылкой: без подтверждения играть нельзя. Она же нужна, чтобы восстановить пароль.": "A confirmation link will be sent to this email: you cannot play until it is confirmed. It is also used to recover your password.",
  "Пришлём письмо со ссылкой — без неё играть нельзя. По этой почте восстанавливают пароль.": "We will send a link by e-mail — you cannot play until you open it. The same e-mail restores your password.",
  // Вход через Google (решение владельца 21.09) и страница «О персональных данных»
  "Войти через Google": "Sign in with Google", "или": "or",
  "Не удалось войти через Google, попробуйте ещё раз": "Could not sign in with Google, please try again",
  "Почти готово": "Almost done", "Почта подтверждена Google:": "Email confirmed by Google:",
  "Из Google мы храним только почту: имя и фото не запрашиваем.": "From Google we keep only your email: no name or photo is requested.",
  "3–24 символа: буквы, цифры, _ и -": "3–24 characters: letters, digits, _ and -",
  "Никнейм видят другие игроки, потом его не изменить.": "Other players see your nickname; it cannot be changed later.",
  "Вход через Google": "Sign in with Google", "Google привязан": "Google linked", "Google отвязан": "Google unlinked",
  "Google привязан: {email}": "Google linked: {email}",
  "Эта учётка Google уже привязана к другому аккаунту": "This Google account is already linked to another account",
  "Не удалось привязать Google, попробуйте ещё раз": "Could not link Google, please try again",
  "Вход по никнейму и паролю тоже работает. После отвязки войти можно будет только по паролю.": "Signing in with nickname and password works too. After unlinking, only the password sign-in remains.",
  "Отвязать": "Unlink", "Привязать Google": "Link Google",
  "Привяжите Google, чтобы входить одной кнопкой. Из Google мы храним только почту.": "Link Google to sign in with one button. From Google we keep only your email.",
  "О персональных данных": "About personal data",
  "Мы храним столько данных, сколько нужно игре, и ничего сверх этого.": "We keep as much data as the game needs and nothing more.",
  "Что мы храним": "What we keep",
  "Никнейм, почту и, если вы его указали, имя для команды. Пароль хранится только в виде хеша: прочитать его нельзя.": "Your nickname, email and, if you gave one, a name for your team. The password is stored only as a hash: it cannot be read.",
  "Игровые действия: взятые и сданные дела, ответы в городах, выученные стихи, ходы команды. Это и есть игра — без них она не работает.": "Game actions: deeds taken and submitted, answers in cities, verses learned, team moves. That is the game itself: it does not work without them.",
  "Если вы входите через Google, из Google мы берём только почту и служебный идентификатор учётки. Имя, фото и другие данные Google не запрашиваются и не сохраняются.": "If you sign in with Google, we take from Google only your email and a technical account identifier. Your name, photo and other Google data are neither requested nor stored.",
  "Чего мы не храним": "What we do not keep",
  "Фотографии и видео людей к нам не загружаются: при сдаче дела вы даёте только ссылку на файл там, где он лежит у вас. Снимать людей можно только с их согласия — это в кодексе каждого дела.": "Photos and videos of people are not uploaded to us: when submitting a deed you give only a link to the file where you keep it. People may be filmed only with their consent — it is in the code of every deed.",
  "Мы не следим за вами вне игры, не продаём и не передаём данные третьим лицам, рекламы нет.": "We do not track you outside the game, do not sell or pass data to third parties, and there are no ads.",
  "Кто что видит": "Who sees what",
  "Участники команды видят ваш никнейм, имя для команды и то, что вы делаете в игре. Администраторы игры видят все игровые данные своей игры: сдачи дел, ссылки, ответы, ходы команд.": "Team members see your nickname, your team name and what you do in the game. Game administrators see all game data of their game: deed submissions, links, answers, team moves.",
  "Администратор платформы видит только обобщённые числа (сколько людей играет, сколько дел сдано) и обращения в поддержку — без содержимого игр и без привязки к людям.": "The platform administrator sees only aggregated numbers (how many people play, how many deeds are submitted) and support requests — without game contents and without linking to people.",
  "Как удалить учётку": "How to delete your account",
  "Напишите администратору своей игры или в поддержку (кнопка в меню): учётку и её игровые записи удалят. Записи в летописи команды остаются без вашего имени.": "Write to your game administrator or to support (button in the menu): the account and its game records will be deleted. Entries in the team chronicle remain without your name.",
  "Cookie": "Cookies",
  "Сайт ставит один cookie — вашу сессию входа (30 дней). Во время входа через Google на несколько минут добавляется служебный cookie для защиты от подделки запроса. Сторонних cookie и счётчиков нет.": "The site sets one cookie — your sign-in session (30 days). During sign-in with Google a technical cookie is added for a few minutes to protect against request forgery. There are no third-party cookies or trackers.",
  "Вопросы — администратору игры или в поддержку.": "Questions — to your game administrator or to support.",
  // Подтверждение почты
  "Подтверждение почты": "Email confirmation",
  "Почта подтверждена": "Email confirmed",
  "Подтвердите почту": "Confirm your email",
  "Войдите в аккаунт и запросите новое письмо: кнопка «Отправить ещё раз».": "Sign in and request a new message with the “Send again” button.",
  "Готово: почта подтверждена, можно играть.": "Done: your email is confirmed, you can play.",
  "К моим играм": "To my games",
  "Мы отправили письмо со ссылкой на": "We sent a message with a link to",
  "Откройте ссылку из письма — и эта страница сама сменится на игру.": "Open the link from the message and this page will switch to the game by itself.",
  "Не пришло — проверьте «Спам» или отправьте письмо ещё раз. Ссылка действует сутки.": "Nothing arrived? Check your spam folder or send the message again. The link is valid for 24 hours.",
  "Другая почта": "Another email",
  "Сохранить и выслать письмо": "Save and send the message",
  "Отправить ещё раз": "Send again",
  "Ошиблись в почте? Изменить": "Wrong email? Change it",
  "Нужна для восстановления пароля и уведомлений. Новую почту нужно будет подтвердить по ссылке из письма.": "Needed for password recovery and notifications. A new email must be confirmed via the link in the message.",
  "Ко входу": "Back to sign in",
  // Восстановление пароля
  "Письмо отправлено": "Email sent",
  "Ссылка действует час. Не пришло — проверьте «Спам».": "The link is valid for one hour. Nothing arrived? Check your spam folder.",
  "Почты в аккаунте не было?": "No email on the account?",
  "Создайте новый аккаунт и попросите капитана прислать приглашение в команду.": "Create a new account and ask your captain to send a team invitation.",
  "Отправка писем на сервере пока не настроена, восстановить пароль сейчас нельзя. Обратитесь к администратору игры.": "Email is not set up on the server yet, so the password cannot be recovered right now. Contact the game administrator.",
  "Пришлём ссылку на почту, указанную в аккаунте.": "We will send a link to the email listed in your account.",
  // Новый пароль
  "Повторите пароль": "Repeat password",
  // Приглашение
  "Приглашение в команду": "Team invitation",
  "Попросите у капитана новую ссылку-приглашение.": "Ask your captain for a new invitation link.",
  "На главную": "Home",
  "Вы уже в команде «{name}» этой игры.": "You are already in the team “{name}” of this game.",
  "Открыть карту": "Open the map",
  // Главная
  "команда": "team", "команды": "teams",
  "Вас ещё не пригласили в команду. Попросите у капитана ссылку-приглашение.": "You have not been invited to a team yet. Ask your captain for an invitation link.",
  // Новая игра
  "Церковь": "Church",
  "Карту, старты и остальное настроите на странице игры.": "The map, starts and everything else are set up on the game page.",
  // Аккаунт
  "суперадмин": "superadmin",
  "нельзя изменить": "cannot be changed",
  "Имя в команде": "Name in the team",
  "Нужна для восстановления пароля и уведомлений.": "Needed for password recovery and notifications.",
  "Для писем и восстановления пароля. Новую почту подтвердите по ссылке из письма.": "For e-mails and password recovery. Confirm a new e-mail via the link we send.",
  "Ссылка для сброса пароля": "Password reset link",
};
