/** EN-строки области «player»: карта, HUD, меню, дело, город, задание, испытание, проходы, «Как играть». Ключ — русская строка как в коде. */
export const PLAYER: Record<string, string> = {
  // Служебные состояния страницы команды
  "Не удалось открыть команду": "Could not open the team", "Загружаем карту…": "Loading the map…", "К странице игры": "To the game page",
  "Вы администратор этой игры, а не участник команды. Карта команды с туманом видна только её участникам; вся карта и ход всех команд — на странице игры.": "You are an administrator of this game, not a team member. A team's fogged map is visible only to its members; the whole map and every team's progress are on the game page.",
  "Игра завершена. Итоги — на странице игры у администратора.": "The game is over. The results are on the administrator's game page.",
  "Игра ещё не началась. Когда администратор начнёт её, здесь появится карта.": "The game has not started yet. When the administrator starts it, the map will appear here.",
  "Пока можно назначить роли участникам: они дают команде разведку, подсказки и переговоры.": "Meanwhile you can assign roles: they give the team scouting, hints and negotiations.",
  "Как играть": "How to play", "Назад": "Back",
  // HUD и меню
  "Меню": "Menu", "Меню · требует внимания: {n}": "Menu · needs attention: {n}", "Меню команды": "Team menu", "Навигация": "Navigation",
  "Приблизить": "Zoom in", "Отдалить": "Zoom out", "вы капитан": "you are the captain",
  "Игра завершена: победила «{team}»": "Game over: “{team}” wins",
  "Наши дела": "Our deeds", "Дела ждут на карте: нажмите на метку на стороне.": "Deeds are waiting on the map: tap a marker on a side.",
  "Испытания": "Trials", "Сейчас испытаний нет.": "No trials right now.", "Испытание · {city}": "Trial · {city}",
  "Вы — претенденты": "You are the challengers", "Вы — хранители": "You are the keepers", "осталось {t}": "{t} left", "ваш ход": "your move",
  "Пока нечего показать.": "Nothing to show yet.", "выиграли {n}": "won {n}", "устояли {n}": "held {n}", "потеряли {n}": "lost {n}",
  "Города": "Cities", "потерян": "lost", "Игра идёт до {d}": "The game runs until {d}",
  "город": "city", "города": "cities", "дело": "deed", "дела": "deeds", "перекрёсток": "crossroads", "перекрёстка": "crossroads", "перекрёстков": "crossroads",
  "стих": "verse", "стиха": "verses", "стихов": "verses",
  // Состав и роли
  "Роль: {name}": "Role: {name}", "Что даёт роль": "What the role gives",
  "Бросает вызов и отвечает на испытания, уступает город, переносит столицу, назначает роли.": "Issues challenges and answers trials, yields a city, moves the capital, assigns roles.",
  "Раз в неделю может разведать, что за стороной: город или развилка.": "Once a week can scout what lies beyond a side: a city or a crossroads.",
  "Раз в неделю открывает подсказку к одному заданию города — текст района.": "Once a week opens a hint for one city task — the district text.",
  "Отправляет запросы прохода другим командам и отвечает на их запросы.": "Sends passage requests to other teams and answers theirs.",
  "Сдаёт дела за команду и следит, чтобы ссылки и фото были приложены.": "Submits deeds for the team and makes sure links and photos are attached.",
  // Карточка дела
  "Фото": "Photo", "Видео": "Video", "Отчёт": "Report", "Подтверждение": "Confirmation", "Сдать": "Submit", "Взял: {name}": "Taken by {name}",
  "Администратор вернул дело: «{comment}». Исправьте и сдайте снова.": "The administrator returned the deed: “{comment}”. Fix it and submit again.",
  "Администратор вернул дело. Исправьте и сдайте снова.": "The administrator returned the deed. Fix it and submit again.",
  "Разведка: за этой стороной город.": "Scouting: there is a city beyond this side.", "Разведка: за этой стороной развилка.": "Scouting: there is a crossroads beyond this side.",
  "Разведка: там город": "Scouting: it is a city",
  "Ветхий Завет": "Old Testament", "Новый Завет": "New Testament",
  "Морской путь: корабль из порта. Когда дело одобрят, капитан выберет на карте, куда высадиться на другом острове.": "Sea route: a ship from the port. Once the deed is approved, the captain picks on the map where to land on the other island.",
  "Выбрать место высадки": "Choose a landing spot", "Дело одобрено: капитан выбирает место высадки.": "The deed is approved: the captain is choosing where to land.",
  "Узел откроется, и с него пойдут дела по другому острову. Вернуться назад можно только с портом.": "The fork opens and deeds on the other island start from it. You can only sail back from a port.",
  "Высадиться здесь?": "Land here?", "Высадиться": "Land", "Команда высадилась на другом острове": "The team has landed on the other island",
  "Выберите на другом острове место высадки": "Choose a landing spot on the other island", "Капитан выбирает место высадки": "The captain is choosing where to land", "Позже": "Later",
  "Взять дело": "Take the deed", "Разведать · раз в неделю": "Scout · once a week", "Сдано на проверку": "Submitted for review",
  "Вместо дела — пожертвование в кассу церкви (от {min} {cur})": "Instead of the deed — a donation to the church (from {min} {cur})",
  "Отказаться от дела": "Give up the deed", "Отказаться от дела?": "Give up the deed?", "Отказаться": "Give up",
  "Дело снова станет свободным, набранный текст пропадёт.": "The deed becomes open again; the typed text will be lost.", "Дело снова свободно": "The deed is open again",
  "Вашему городу {city} брошен вызов: {n} стихов": "Your city {city} has been challenged: {n} verses",
  "Вызов городу {city} принят: пошло время ответа": "The challenge to {city} is accepted: response time is running",
  // Карта
  "ждём прохода": "awaiting passage", "проход закрыт": "passage closed",
  // Попап города
  "Ваш город": "Your city", "Город команды «{team}»": "City of team “{team}”", "Город в руинах": "City in ruins", "Свободный город": "Free city", "Столица": "Capital",
  "Шаги": "Steps", "Порядок": "Order", "Конверт": "Envelope",
  "Расставьте районы по порядку книги": "Arrange the districts in the order of the book", "Тяните за ручку или пользуйтесь стрелками.": "Drag by the handle or use the arrows.",
  "Не на месте: {n} · попытка {k}": "Out of place: {n} · attempt {k}", "Порядок верный: районы открыты": "The order is right: the districts are open",
  "Решите задание в каждом районе": "Solve the task in every district", "закрыто": "closed", "Задания по всей книге": "Whole-book tasks",
  "По всей книге": "Whole book", "По нескольким районам": "Several districts", "По этому району": "This district", "По районам: {list}": "Districts: {list}",
  "Получите конверт с ключом": "Get the envelope with the key", "Шифр города": "City cipher", "Соберётся, когда решите все районы": "Completes when all districts are solved",
  "Город в руинах: его можно занять без конверта.": "The city is in ruins: it can be occupied without an envelope.",
  "Назовите шифр адресату «{label}» ({kind}) и получите конверт с ключом.": "Tell the cipher to the recipient “{label}” ({kind}) and get the envelope with the key.",
  "Назовите шифр адресату, к которому вас направили, и получите конверт с ключом.": "Tell the cipher to the recipient you were sent to and get the envelope with the key.",
  "Подождите {n} с": "Wait {n} s", "Ключ напечатан в конверте: не меньше 4 знаков": "The key is printed in the envelope: at least 4 characters",
  "Город ваш": "The city is yours", "Город ваш.": "The city is yours.", "Город ваш. Это ваша столица": "The city is yours. It is your capital",
  "Город ваш — это ваша столица.": "The city is yours — it is your capital.", "Город ваш — это ваша вторая столица.": "The city is yours — it is your second capital.",
  "Перенести столицу в этот город?": "Move the capital to this city?", "Это единственный перенос за игру.": "This is the only move per game.",
  "Проход": "Passage", "Испытание": "Trial",
  // Задание
  "К районам": "To districts", "Район {n}": "District {n}", "Задание {n}": "Task {n}",
  "Чтение {a} / {b} · счёт идёт, пока задание открыто": "Reading {a} / {b} · counts while the task is open",
  "Попытка {a} из {b}": "Attempt {a} of {b}", "Попытка {a} из {b}: после неверного ответа задание закроется на сутки.": "Attempt {a} of {b}: after a wrong answer the task closes for a day.",
  "Задание закрыто": "The task is closed",
  "Вы написали администратору: «{m}». Ждём ответа.": "You wrote to the administrator: “{m}”. Waiting for a reply.",
  "Администратор ответил: {a}": "The administrator replied: {a}", "задание оставлено закрытым": "the task stays closed", "Написать администратору": "Write to the administrator",
  "Сообщение отправлено администратору": "Message sent to the administrator",
  "Подсказка пророка · текст района {verses}": "Prophet's hint · district text {verses}", "Подсказка пророка · раз в неделю": "Prophet's hint · once a week",
  "Верно. Знак шифра: {f}": "Correct. Cipher sign: {f}", "Выполнено. Знак шифра: {f}": "Done. Cipher sign: {f}", "Варианты ответа": "Answer options",
  // Испытание
  "Испытание города": "City trial", "Уровень испытания: {n}": "Trial level: {n}", "в книге {n}": "{n} in the book",
  "Город устоял окончательно: испытать его больше нельзя.": "The city has held for good: it can no longer be challenged.",
  "Ставка, стихов": "Bid, verses", "минимум {n}": "minimum {n}", "включая штраф {n} за незавершённые вызовы": "including a {n} penalty for unfinished challenges", "в очереди уже {n}": "{n} already in the queue",
  "Как проходит испытание": "How a trial works",
  "Ставка — сколько стихов команда выучит в сумме по участникам: каждый учит свою часть или весь отрывок. Отрывок выберет игра.": "The bid is how many verses the team will learn in total across members: each learns a part or the whole passage. The game picks the passage.",
  "Каждый отмечает выученные стихи и прикладывает ссылку на видео. Когда сумма набрана, капитан отправляет вызов на проверку администратору.": "Everyone ticks the verses they learned and attaches a video link. When the total is reached, the captain sends the challenge to the administrator for review.",
  "Хранителям даётся столько же времени, сколько ушло у претендентов: они выбирают отрывок из книги и учат не меньше стихов. Ничья — в пользу хранителей.": "The keepers get as much time as the challengers took: they choose a passage from the book and learn at least as many verses. A tie goes to the keepers.",
  "Не завершённый за 14 дней вызов сгорает, и следующая ставка на этот город для команды растёт на 5 стихов.": "A challenge not finished within 14 days expires, and the team's next bid for this city grows by 5 verses.",
  "Испытать город со ставкой {n}?": "Challenge the city with a bid of {n}?",
  "Команда обязуется выучить {n} в сумме по участникам. Игра выдаст случайный отрывок; с этого момента идёт время вызова, не больше 14 дней.": "The team commits to learning {n} in total across members. The game gives a random passage; from that moment challenge time runs, up to 14 days.",
  "Вызов брошен: отрывок выдан": "Challenge issued: the passage is given",
  "Вы — претенденты, против «{team}»": "You are the challengers, against “{team}”", "Вы — хранители, вызов от «{team}»": "You are the keepers, challenged by “{team}”",
  "Ставка: {n}": "Bid: {n}", "вызов: {n} за {time}": "challenge: {n} in {time}", "вызов на проверке": "challenge under review", "ответ на проверке": "response under review",
  "Претенденты учат отрывок. Когда администратор примет их записи, у вас будет столько же времени на ответ.": "The challengers are learning the passage. When the administrator accepts their recordings, you will have the same amount of time to respond.",
  "Выучено {a} из {b} · принято {c}": "Learned {a} of {b} · accepted {c}", "Не хватает {n}": "{n} short",
  "Отправить вызов на проверку?": "Send the challenge for review?", "Отправить ответ на проверку?": "Send the response for review?",
  "Выучено {a} из {b}. После отправки добавлять стихи нельзя; время вызова остановится.": "Learned {a} of {b}. After sending, no verses can be added; challenge time stops.",
  "Выучено {a} из {b}. После отправки добавлять стихи нельзя.": "Learned {a} of {b}. After sending, no verses can be added.",
  "Отправлено на проверку администратору": "Sent to the administrator for review",
  "Уступить город?": "Yield the city?", "Город перейдёт претендентам. Если это столица — команда выбывает из игры.": "The city passes to the challengers. If it is the capital, the team leaves the game.",
  "Отрывок {ref}": "Passage {ref}", "вы выучили {a} из {b}": "you learned {a} of {b}", "Ссылки на видео": "Video links", "Засчитать {n}": "Count {n}",
  "Засчитано {a}. Команда выучила {s}": "Counted {a}. The team has learned {s}", "Комментарий: {c}": "Comment: {c}",
  "Глава": "Chapter", "начало {ref}, выберите конец": "start {ref}, choose the end",
  "Нажмите первый и последний стих отрывка из книги {name}. Нужно не меньше {n} на команду.": "Tap the first and the last verse of a passage from {name}. At least {n} per team are needed.",
  // Проходы
  "Проходы": "Passages", "Запросов прохода нет.": "No passage requests.", "Запросов прохода пока не было.": "No passage requests yet.",
  "Проход открыт: стороны за городом доступны. Владелец может закрыть его в любой момент.": "Passage is open: the sides beyond the city are available. The owner can close it at any time.",
  "Ответ: «{a}»": "Answer: “{a}”", "Запрос отправлен {d}. Ответ до {until}; молчание — отказ.": "Request sent {d}. Answer due {until}; silence means no.",
  "Дальше через чужой город идти нельзя без разрешения владельца.": "You cannot go on through another team's city without the owner's permission.", "Последний ответ: {s}": "Last answer: {s}",
  "Сообщение владельцу": "Message to the owner", "В проходе отказано": "Passage declined",
  "Отозвать проход для «{team}» через {book}?": "Revoke passage for “{team}” through {book}?", "Их уже взятые дела останутся, новые дела за городом им не достанутся.": "Deeds they have already taken stay; they get no new deeds beyond the city.",
  "Отозвать проход": "Revoke passage", "Проход отозван": "Passage revoked", "Ответить до {d} · молчание — отказ": "Answer by {d} · silence means no",
  "Проход для «{team}»": "Passage for “{team}”", "Наш запрос: {book}": "Our request: {book}", "владелец «{team}»": "owner “{team}”", "проход через {book}": "passage through {book}",
  // Как играть — полная инструкция со скриншотами
  "Как играть?": "How to play?", "Разделы": "Sections",
  "Полная инструкция по игре. Картинки — с настоящих экранов игры и обновляются вместе с ней.": "The complete guide to the game. The pictures are real game screens and are updated together with it.",
  "Вход и приглашение": "Signing in and invitations",
  "Игра открывается в браузере телефона или компьютера, ничего устанавливать не нужно. Зарегистрируйтесь по никнейму и паролю: почта не обязательна, но с ней можно восстановить пароль.": "The game opens in the browser on a phone or a computer; nothing needs installing. Register with a nickname and a password: an email is optional, but with it you can recover your password.",
  "В команду попадают по ссылке-приглашению от капитана или администратора. Откройте ссылку, войдите — и команда появится на главной.": "You join a team through an invitation link from the captain or the administrator. Open the link, sign in, and the team appears on the home screen.",
  "Вход и регистрация. Справа сверху — переключение языка.": "Sign in and registration. Top right: language switch.",
  "Главная: ваши команды и игры, кнопка «Как играть?».": "Home: your teams and games, the “How to play?” button.",
  "Карту двигают одним пальцем, приближают щипком двумя или колесом мыши. Кнопки справа: вся карта, к старту, приблизить, отдалить. Кнопка меню слева сверху открывает дела команды, испытания, положение команд и состав.": "Drag the map with one finger, zoom with a two-finger pinch or the mouse wheel. Buttons on the right: whole map, to the start, zoom in, zoom out. The menu button at the top left opens the team’s deeds, trials, standings and roster.",
  "Открытая часть карты: перекрёстки, стороны с метками дел, город команды.": "The revealed part of the map: crossroads, sides with deed markers, the team’s city.",
  "Отдалённый вид: туман над неоткрытыми землями, подписи городов.": "Zoomed out: fog over unexplored lands, city labels.",
  "Корабль — обычное дело. Когда его одобрят, капитан выбирает на карте пустую береговую развилку другого острова и высаживается там. Вернуться можно так же, взяв порт на другом острове. Внутри одного острова корабли не ходят.": "A ship is an ordinary deed. Once it is approved, the captain picks an empty coastal crossroads on the other island and lands there. You can return the same way by taking a port on the other island. Ships do not sail within one island.",
  "Оба острова целиком. Между ними — море с островками и живностью.": "Both islands in full. Between them: the sea with islets and wildlife.",
  "Дело — настоящее служение: помочь семье, навестить одинокого человека, поработать в лагере. Метка дела стоит на стороне; нажмите её — откроется карточка: направление, что нужно сделать и чем подтвердить.": "A deed is real ministry: helping a family, visiting a lonely person, working at a camp. The deed marker sits on a side; tap it to open the card: the direction, what to do and how to confirm it.",
  "«Взять дело» — дело закрепляется за вами. Сделали — нажмите «Сдать» и приложите ссылку на фото, видео или короткий отчёт (файлы в игру не загружаются, только ссылки на них).": "“Take the deed” assigns it to you. When done, tap “Submit” and attach a link to a photo, a video or a short report (files are not uploaded to the game, only links to them).",
  "Администратор проверяет сдачу. Принятое дело открывает сторону; возвращённое можно исправить и сдать снова. Несколько участников могут делать разные дела одновременно. Летописец может сдавать дела за команду.": "The administrator reviews the submission. An accepted deed opens the side; a returned one can be fixed and submitted again. Several members can do different deeds at the same time. The chronicler can submit deeds for the team.",
  "Карточка дела: направление, описание, чем подтвердить, кнопка «Взять дело».": "Deed card: direction, description, how to confirm, the “Take the deed” button.",
  "Город — книга Библии. Нажмите подпись города — откроется его страница с тремя шагами: Порядок, Районы, Конверт.": "A city is a book of the Bible. Tap the city label to open its page with three steps: Order, Districts, Envelope.",
  "Порядок: расставьте районы, как сцены идут в книге. Районы: в каждом решите задание, читая текст (у заданий с выбором две попытки, потом задание закрывается на сутки). Каждое решённое задание даёт знак шифра.": "Order: arrange the districts the way the scenes go in the book. Districts: solve the task in each one while reading the text (multiple-choice tasks allow two attempts, then the task locks for a day). Every solved task gives one sign of the cipher.",
  "Конверт: когда все районы решены, шифр собран. Назовите его адресату, к которому вас направила игра, и получите конверт с ключом. Ключ берёт город. Первый взятый город — столица команды; один раз за игру капитан может перенести столицу.": "Envelope: when all districts are solved, the cipher is complete. Tell it to the recipient the game sends you to and receive the envelope with the key. The key takes the city. The first city taken is the team’s capital; once per game the captain may move the capital.",
  "Страница города: шаги Порядок → Районы → Конверт, шифр города.": "City page: the steps Order → Districts → Envelope, the city cipher.",
  "Роли и меню команды": "Roles and the team menu",
  "В меню команды: наши дела, испытания, положение команд, проходы, состав с ролями, уведомления. Включите уведомления, чтобы не пропустить проверку дела, испытание или запрос прохода.": "In the team menu: our deeds, trials, standings, passages, the roster with roles, notifications. Turn notifications on so you do not miss a deed review, a trial or a passage request.",
  "Меню команды: дела, испытания, положение команд, состав.": "Team menu: deeds, trials, standings, roster.",
  "Для администратора": "For the administrator",
  "Администратор создаёт игру, генерирует карту (можно сколько угодно раз, пока не понравится), создаёт команды и раздаёт ссылки-приглашения капитанам и участникам, заполняет набор дел (есть стандартный) и стартует игру.": "The administrator creates the game, generates the map (as many times as needed until it looks right), creates teams and hands out invitation links to captains and members, fills in the set of deeds (a default set is available) and starts the game.",
  "У администратора карта во весь экран, а разделы — кнопки сбоку (на телефоне снизу): Обзор, Команды, Дела, Проверка, Настройки; нажатие открывает раздел над картой. Во время игры администратор проверяет сдачи дел и видео испытаний в «Проверке», следит за положением команд в «Обзоре» и на карте, при необходимости назначает города и завершает игру.": "The administrator sees the map full screen, with the sections as buttons on the side (at the bottom on a phone): Overview, Teams, Deeds, Review, Settings; tapping one opens the section over the map. During the game the administrator reviews deed submissions and trial videos in “Review”, follows the standings in the “Overview” and on the map, assigns cities when needed and finishes the game.",
  "Карта администратора: все города, номера, пути команд; кнопки разделов слева.": "Administrator’s map: all cities, numbers, team routes; section buttons on the left.",
  "Пароли участников администратор не видит и не меняет: восстановление — только через почту самого участника.": "The administrator never sees or changes members’ passwords: recovery goes only through the member’s own email.",
  "Обзор игры: что ждёт проверки, положение команд, адресаты конвертов.": "Game overview: what awaits review, standings, envelope recipients.",
  "Команды и приглашения.": "Teams and invitations.", "Набор дел игры.": "The game’s set of deeds.",
  "Проверка: сдачи дел, испытания, проходы.": "Review: deed submissions, trials, passages.",
  "Карта администратора: все города, номера, пути команд.": "Administrator’s map: all cities, numbers, team routes.",
  // Как играть (краткие правила, часть строк общая с полной инструкцией)
  "Два острова и корабли": "Two islands and ships",
  "Карта — два острова: Ветхий Завет и Новый Завет. Старт — на Ветхом. Города на берегу — порты: когда команда берёт порт, у него появляется корабль.": "The map is two islands: the Old Testament and the New Testament. You start on the Old. Coastal cities are ports: when the team takes a port, a ship appears next to it.",
  "Корабль — обычное дело. Когда его одобрят, капитан выбирает на карте пустую береговую развилку другого острова и высаживается там. Вернуться можно так же, взяв порт на другом острове.": "The ship is an ordinary deed. Once it is approved, the captain picks an empty coastal fork on the other island on the map and lands there. You can sail back the same way by taking a port on the other island.",
  "Коротко о главном. Подробности подскажет администратор игры.": "The essentials in brief. The game administrator can tell you more.",
  "Карта и стороны": "Map and sides",
  "Карта скрыта туманом. Команда стоит на перекрёстке и видит дела на сторонах, которые из него выходят, но не видит, что за ними: город или пустая развилка.": "The map is hidden by fog. The team stands at a crossroads and sees the deeds on the sides leading out of it, but not what lies beyond: a city or an empty crossroads.",
  "Пройденная сторона окрашивается в цвет команды и открывает следующий перекрёсток. По открытым перекрёсткам команда ходит свободно.": "A completed side takes the team's colour and opens the next crossroads. The team moves freely across opened crossroads.",
  "Дела": "Deeds",
  "Дело — настоящее служение: помочь семье, навестить одинокого человека, поработать в лагере. Участник берёт дело на карте, выполняет и сдаёт ссылку на фото, видео или короткий отчёт.": "A deed is real service: help a family, visit a lonely person, work at a camp. A member takes a deed on the map, does it and submits a photo or video link or a short report.",
  "Администратор проверяет сдачу. Принятое дело открывает сторону; возвращённое можно исправить и сдать снова. Несколько участников могут делать разные дела одновременно.": "The administrator reviews the submission. An accepted deed opens the side; a returned one can be fixed and submitted again. Several members can do different deeds at the same time.",
  "Города и районы": "Cities and districts",
  "Город — книга Библии. Он поделён на районы — сцены книги. Сначала расставьте районы по порядку, как они идут в книге; затем в каждом районе решите задание, читая текст.": "A city is a book of the Bible. It is divided into districts — scenes of the book. First arrange the districts in the order they appear in the book; then solve the task in each district while reading the text.",
  "У заданий с выбором две попытки, потом задание закрывается на сутки. Каждое решённое задание даёт знак шифра.": "Multiple-choice tasks have two attempts, then the task closes for a day. Every solved task gives a cipher sign.",
  "Шифр и конверт": "Cipher and envelope",
  "Когда все районы решены, шифр собран. Назовите его адресату, к которому вас направила игра, и получите конверт с ключом.": "When all districts are solved, the cipher is complete. Tell it to the recipient the game sent you to and get the envelope with the key.",
  "Ключ из конверта берёт город. Первый взятый город становится столицей команды; один раз за игру капитан может перенести столицу в другой свой город.": "The key from the envelope takes the city. The first city taken becomes the team's capital; once per game the captain can move the capital to another of the team's cities.",
  "Если город уже принадлежит другой команде, его можно испытать. Претенденты называют ставку — сколько стихов из этой книги команда выучит в сумме по участникам. Игра выдаёт случайный отрывок.": "If a city already belongs to another team, it can be challenged. The challengers name a bid — how many verses of this book the team will learn in total across members. The game gives a random passage.",
  "Каждый учит свою часть, записывает видео и отмечает выученные стихи. Когда сумма набрана, капитан отправляет вызов на проверку. У хранителей столько же времени на ответ: они выбирают отрывок из книги и учат не меньше стихов. Ничья — в пользу хранителей.": "Everyone learns their part, records a video and ticks the verses learned. When the total is reached, the captain sends the challenge for review. The keepers get the same amount of time to respond: they choose a passage from the book and learn at least as many verses. A tie goes to the keepers.",
  "Потеря столицы — выход из игры: остальные города команды становятся руинами, их можно занять без конверта. Побеждает команда, владеющая всеми столицами, или к сроку игры — с наибольшим числом городов.": "Losing the capital means leaving the game: the team's other cities become ruins that can be occupied without an envelope. The team that owns all capitals wins, or, at the game deadline, the team with the most cities.",
  "Через чужой город можно пройти, не беря его, но нужно разрешение владельца. Запрос отправляет посол, а без посла — капитан; у владельца три дня на ответ, молчание — отказ.": "You can pass through another team's city without taking it, but you need the owner's permission. The ambassador sends the request, or the captain if there is none; the owner has three days to answer, silence means no.",
  "Разрешение действует, пока владелец его не отзовёт. Уже взятые за городом дела остаются у команды.": "The permission lasts until the owner revokes it. Deeds already taken beyond the city stay with the team.",
  "Роли": "Roles",
  "Капитан бросает вызов и отвечает на испытания, уступает город, переносит столицу и назначает роли. Разведчик раз в неделю узнаёт, что за стороной. Пророк раз в неделю открывает подсказку к заданию. Посол ведёт переговоры о проходах. Летописец сдаёт дела за команду.": "The captain issues challenges and answers trials, yields a city, moves the capital and assigns roles. The scout learns once a week what lies beyond a side. The prophet opens a task hint once a week. The ambassador negotiates passages. The chronicler submits deeds for the team.",
  // Обращение в поддержку из задания
  "Обращение отправлено. Ответ придёт уведомлением и письмом.": "Request sent. The reply will come as a notification and an email.",
  "Обращение в поддержку отправлено {d}. Ждём ответа.": "Support request sent on {d}. Waiting for a reply.", "Ответ поддержки: {a}": "Support reply: {a}", "блокировка снята": "the lock is lifted", "обращение рассмотрено": "the request was reviewed",
  "Написать в поддержку": "Contact support", "Обращение в поддержку": "Support request", "Город, задание {n} и состояние попыток подставятся автоматически. Опишите, что не так.": "The city, task {n} and attempt state are filled in automatically. Describe what is wrong.", "Сообщение": "Message",
  "Тайное дело: ссылку и описание сдачи видит только тот, кто его взял, и проверяющий администратор.": "Secret deed: only the person who took it and the reviewing administrator see the submitted link and note.",
};
